create table chat_topic
(
    conversation_id varchar                             not null
        primary key,
    "user"          varchar(255)                        not null,
    is_user         boolean                             not null,
    topic           varchar(255),
    created_at      timestamp default CURRENT_TIMESTAMP not null,
    updated_at      timestamp default CURRENT_TIMESTAMP
);

create index chat_topic_user_timestamp
    on chat_topic ("user" asc, updated_at desc);

create table chat_message
(
    id              bigint generated by default as identity
        constraint pk_chat_memory
            primary key,
    conversation_id varchar(255),
    content         varchar,
    created_at      timestamp,
    position        bigint                not null,
    summarized      boolean               not null,
    summary         boolean default false not null,
    type            varchar(20)
);

create table documents
(
    id          bigserial
        primary key,
    title       text                                              not null,
    type        text                     default 'document'::text not null,
    parent_id   bigint
        references documents
            on delete cascade,
    updated_at  timestamp with time zone default now()            not null,
    description text,
    position    integer                  default 0                not null,
    is_system   boolean                  default false            not null
);

create index documents_description__index
    on documents using gist (description gist_trgm_ops);

create table document_embeddings
(
    id          bigserial
        primary key,
    document_id bigint                                 not null
        unique
        references documents
            on delete cascade,
    embedding   vector(1024)                           not null,
    model       text                                   not null,
    updated_at  timestamp with time zone default now() not null
);

create index document_embeddings_ivfflat_idx
    on document_embeddings using ivfflat (embedding vector_cosine_ops);

create table embedding_cache
(
    id           bigserial
        primary key,
    text_hash    char(64)                               not null,
    model        text                                   not null,
    embedding    vector                                 not null,
    created_at   timestamp with time zone default now() not null,
    last_used_at timestamp with time zone default now() not null,
    constraint uq_embedding_cache
        unique (text_hash, model)
);

create index idx_embedding_cache_lookup
    on embedding_cache (text_hash, model);

create index idx_embedding_cache_last_used
    on embedding_cache (last_used_at);

create table attachments
(
    id              bigserial
        primary key,
    owner_type      text                                                not null
        constraint attachments_owner_type_check
            check (owner_type = ANY (ARRAY ['document'::text, 'chat'::text])),
    document_id     bigint
        references documents
            on delete cascade,
    conversation_id varchar(255)
        references chat_topic
            on delete cascade,
    file_name       text                                                not null,
    content_type    text                     default 'text/plain'::text not null,
    file_size       bigint                   default 0                  not null,
    content         text,
    summary         text,
    created_at      timestamp with time zone default now()              not null,
    updated_at      timestamp with time zone default now()              not null,
    source_url      text,
    constraint chk_attachment_owner
        check (((owner_type = 'document'::text) AND (document_id IS NOT NULL) AND (conversation_id IS NULL)) OR
               ((owner_type = 'chat'::text) AND (conversation_id IS NOT NULL) AND (document_id IS NULL)))
);

alter table attachments
    owner to knowledgebase;

create index idx_attachments_document
    on attachments (document_id)
    where (document_id IS NOT NULL);

create index idx_attachments_conversation
    on attachments (conversation_id)
    where (conversation_id IS NOT NULL);

create table attachment_embeddings
(
    id            bigserial
        primary key,
    attachment_id bigint                                 not null
        unique
        references attachments
            on delete cascade,
    embedding     vector(1024)                           not null,
    model         text                                   not null,
    updated_at    timestamp with time zone default now() not null
);

create index attachment_embeddings_ivfflat_idx
    on attachment_embeddings using ivfflat (embedding vector_cosine_ops);

INSERT INTO documents (id, title, type, parent_id, updated_at, description, position, is_system) VALUES (1, 'Проект KB', 'folder', null, '2026-05-21 17:35:13.888951 +00:00', e'# Общая информация
', 0, true);
INSERT INTO documents (id, title, type, parent_id, updated_at, description, position, is_system) VALUES (2, 'Введение', 'document', 1, '2026-05-21 17:32:42.552937 +00:00', e'# Общие сведения
', 0, true);
INSERT INTO documents (id, title, type, parent_id, updated_at, description, position, is_system) VALUES (3, 'Backend', 'folder', 1, '2026-05-21 17:33:54.728050 +00:00', e'# Backend
', 1, true);
INSERT INTO documents (id, title, type, parent_id, updated_at, description, position, is_system) VALUES (4, 'Fronend', 'folder', 1, '2026-05-21 17:33:42.528237 +00:00', e'# Frontend
', 2, true);

SELECT setval('documents_id_seq', (SELECT MAX(id) FROM documents));

