-- Очередь сообщений, отправленных в чат во время активного прогона. Строка живёт от приёма
-- до ближайшего безопасного «окна» доставки в chat_message: между ответами инструментов и
-- следующим запросом к модели (InterjectionAdvisor), в терминальной обработке прогона или
-- при восстановлении после падения процесса (PendingMessageService). Отдельная таблица, а не
-- ряд chat_message с флагом: во время выполнения инструментов хвост истории — это
-- assistant.tool_calls без TOOL-ответа, и USER-ряд с позицией max+1 встал бы внутрь пары,
-- сломав протокольный порядок для модели.
--
-- Доставка — claim-through-delete: строку переносит тот, чей DELETE её застал, поэтому
-- конкурирующие точки доставки не задваивают сообщение и без внешних замков.
--
-- meta — JSON ChatMessageMeta (contextItems вопроса), тем же конвертером, что и
-- chat_message.meta. model/mode/project — снимок выбора на момент отправки: если прогон
-- завершится раньше доставки, follow-up прогон обязан поехать на том, что пользователь
-- выбрал тогда, а не на том, что окажется у чата к тому моменту.
CREATE TABLE chat_pending_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL
        REFERENCES chat_topic (conversation_id) ON DELETE CASCADE,
    "user"          VARCHAR(255) NOT NULL,
    content         TEXT         NOT NULL,
    client_msg_id   VARCHAR(255),
    meta            TEXT,
    model           VARCHAR(255),
    mode            VARCHAR(255),
    project         VARCHAR(255),
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_chat_pending_message_conversation ON chat_pending_message (conversation_id);
