export const CHAT_EVENT = {
  MESSAGE_QUEUED: 'MESSAGE_QUEUED',
  USER_MESSAGE: 'USER_MESSAGE',
  RUN_STARTED: 'RUN_STARTED',
  STREAM: 'STREAM',
  TOOL_CALL: 'TOOL_CALL',
  TOOL_CALLS: 'TOOL_CALLS',
  RUN_USAGE: 'RUN_USAGE',
  RUN_DONE: 'RUN_DONE',
  RUN_STOPPED: 'RUN_STOPPED',
  RUN_ERROR: 'RUN_ERROR',
  COMPACT_STARTED: 'COMPACT_STARTED',
  COMPACT_DONE: 'COMPACT_DONE',
  COMPACT_ERROR: 'COMPACT_ERROR',
  GIT_COMMAND: 'GIT_COMMAND',
  REPLAY_GAP: 'REPLAY_GAP',
};

export const FINISH_REASON = {
  TOOL_CALLS: 'TOOL_CALLS',
};
