export const CHAT_EVENT = {
  USER_MESSAGE: 'USER_MESSAGE',
  RUN_STARTED: 'RUN_STARTED',
  TOOL_PREPARING: 'TOOL_PREPARING',
  STREAM: 'STREAM',
  TOOL_CALL: 'TOOL_CALL',
  TOOL_CALLS: 'TOOL_CALLS',
  RUN_DONE: 'RUN_DONE',
  RUN_STOPPED: 'RUN_STOPPED',
  RUN_ERROR: 'RUN_ERROR',
};

export const FINISH_REASON = {
  TOOL_CALLS: 'TOOL_CALLS',
};
