CREATE TABLE chat_topic
(
    CONVERSATION_ID VARCHAR                             NOT NULL
        PRIMARY KEY,
    "user"          VARCHAR(255)                        NOT NULL,
    IS_USER         BOOLEAN                             NOT NULL,
    TOPIC           VARCHAR(255),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX chat_topic_user_timestamp
    ON chat_topic ("user" ASC, UPDATED_AT DESC);

CREATE TABLE chat_message
(
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_CHAT_MEMORY
            PRIMARY KEY,
    CONVERSATION_ID VARCHAR(255),
    CONTENT         VARCHAR,
    CREATED_AT      TIMESTAMP,
    POSITION        BIGINT                NOT NULL,
    SUMMARIZED      BOOLEAN               NOT NULL,
    SUMMARY         BOOLEAN DEFAULT FALSE NOT NULL,
    TYPE            VARCHAR(20)
);


CREATE TABLE documents
(
    ID                     BIGSERIAL
        PRIMARY KEY,
    TITLE                  TEXT                                              NOT NULL,
    TYPE                   TEXT                     DEFAULT 'document'::TEXT NOT NULL,
    PARENT_ID              BIGINT
        REFERENCES documents
            ON DELETE CASCADE,
    UPDATED_AT             TIMESTAMP WITH TIME ZONE DEFAULT NOW()            NOT NULL,
    DESCRIPTION            TEXT,
    POSITION               INTEGER                  DEFAULT 0                NOT NULL,
    IS_SYSTEM              BOOLEAN                  DEFAULT FALSE            NOT NULL,
    VERSION                INTEGER                  DEFAULT 1                NOT NULL,
    SUMMARY                TEXT,
    SUMMARY_SOURCE_VERSION INTEGER,
    DESCRIPTION_VERSION    INTEGER                  DEFAULT 1                NOT NULL
);

CREATE TABLE document_embeddings
(
    ID          BIGSERIAL
        PRIMARY KEY,
    DOCUMENT_ID BIGINT                                 NOT NULL
        UNIQUE
        REFERENCES documents
            ON DELETE CASCADE,
    EMBEDDING   TEXT ARRAY                             NOT NULL,
    MODEL       TEXT                                   NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);


CREATE TABLE embedding_cache
(
    ID           BIGSERIAL
        PRIMARY KEY,
    TEXT_HASH    CHAR(64)                               NOT NULL,
    MODEL        TEXT                                   NOT NULL,
    EMBEDDING    TEXT ARRAY                             NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    LAST_USED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT UQ_EMBEDDING_CACHE
        UNIQUE (TEXT_HASH, MODEL)
);


CREATE TABLE attachments
(
    ID              BIGSERIAL
        PRIMARY KEY,
    OWNER_TYPE      TEXT                                                NOT NULL
        CONSTRAINT ATTACHMENTS_OWNER_TYPE_CHECK
            CHECK (OWNER_TYPE in ('document', 'chat')),
    DOCUMENT_ID     BIGINT
        REFERENCES documents
            ON DELETE CASCADE,
    CONVERSATION_ID VARCHAR(255)
        REFERENCES CHAT_TOPIC
            ON DELETE CASCADE,
    FILE_NAME       TEXT                                                NOT NULL,
    CONTENT_TYPE    TEXT                     DEFAULT 'text/plain'::TEXT NOT NULL,
    FILE_SIZE       BIGINT                   DEFAULT 0                  NOT NULL,
    CONTENT         TEXT,
    SUMMARY         TEXT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()              NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT NOW()              NOT NULL,
    SOURCE_URL      TEXT,
    CONSTRAINT CHK_ATTACHMENT_OWNER
        CHECK (((OWNER_TYPE = 'document') AND (DOCUMENT_ID IS NOT NULL) AND (CONVERSATION_ID IS NULL)) OR
               ((OWNER_TYPE = 'chat') AND (CONVERSATION_ID IS NOT NULL) AND (DOCUMENT_ID IS NULL)))
);


CREATE INDEX IDX_ATTACHMENTS_DOCUMENT
    ON ATTACHMENTS (DOCUMENT_ID);

CREATE INDEX IDX_ATTACHMENTS_CONVERSATION
    ON ATTACHMENTS (CONVERSATION_ID);

CREATE TABLE attachment_embeddings
(
    ID            BIGSERIAL
        PRIMARY KEY,
    ATTACHMENT_ID BIGINT                                 NOT NULL
        UNIQUE
        REFERENCES ATTACHMENTS
            ON DELETE CASCADE,
    EMBEDDING     TEXT ARRAY                             NOT NULL,
    MODEL         TEXT                                   NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE document_history
(
    ID                     BIGSERIAL
        PRIMARY KEY,
    DOCUMENT_ID            BIGINT                   NOT NULL
        REFERENCES documents
            ON DELETE CASCADE,
    VERSION                INTEGER                  NOT NULL,
    TITLE                  TEXT                     NOT NULL,
    TYPE                   TEXT                     NOT NULL,
    DESCRIPTION            TEXT,
    UPDATED_AT             TIMESTAMP WITH TIME ZONE NOT NULL,
    SUMMARY                TEXT,
    SUMMARY_SOURCE_VERSION INTEGER,
    DESCRIPTION_VERSION    INTEGER DEFAULT 1        NOT NULL,
    CONSTRAINT UQ_DOCUMENT_HISTORY_VERSION
        UNIQUE (DOCUMENT_ID, VERSION)
);

CREATE INDEX IDX_DOCUMENT_HISTORY_DOCUMENT_ID
    ON DOCUMENT_HISTORY (DOCUMENT_ID ASC, VERSION DESC);

