-- Сводки, которые фоновая суммаризация уже написала, но в историю ещё не применила. Между
-- «написали» и «применили» стоит цена, которой у сжатия иначе не видно: провайдер кэширует
-- промпт с первого байта, и любая правка истории обесценивает кэш всего чата. Сразу после
-- ответа этот кэш горячий, и подмена куска истории стоит полной оплаты следующего запроса;
-- после паузы он всё равно протух, и та же подмена бесплатна. Поэтому раунд паркует результат
-- здесь, а применяет его PendingSummaryService — по паузе от последнего ряда чата или, если
-- ждать больше нельзя, по размеру контекста (предел берётся из параметров модели).
--
-- Очередь, а не одна строка на чат: пока применения нет, разговор продолжается, и следующий
-- раунд сжимает то, что накопилось ЗА уже припаркованным (припаркованное он получает
-- контекстом — см. SummarizeService). Диапазоны строк очереди не пересекаются и идут подряд,
-- применяются они разом и в порядке start_position.
--
-- Позиции и текст — ровно то, что запишет SummaryWriter.SummaryRow, посчитанное на момент
-- парковки. meta — мета будущих рядов в том виде, в каком она известна тогда же: спаны
-- проектов уедут на строку-сводку, замер раунда — на видимую плашку. Compact-часть плашки
-- достраивается при применении: в ней id строки-сводки, которой до записи ещё нет.
CREATE TABLE chat_pending_summary (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id    VARCHAR(255) NOT NULL
        REFERENCES chat_topic (conversation_id) ON DELETE CASCADE,
    start_position     BIGINT       NOT NULL,
    end_position       BIGINT       NOT NULL,
    summary_position   BIGINT       NOT NULL,
    summary_created_at TIMESTAMP    NOT NULL,
    text               TEXT         NOT NULL,
    messages           INT          NOT NULL,
    summary_chars      INT          NOT NULL,
    meta               TEXT,
    created_at         TIMESTAMP    NOT NULL
);

-- Читают эту таблицу только по чату, и на каждом вопросе: с ним сверяется, не пора ли
-- применить (PendingSummaryService.applyIfPaused).
CREATE INDEX idx_chat_pending_summary_conversation
    ON chat_pending_summary (conversation_id, start_position);
