CREATE TABLE phrase
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    CATEGORY   VARCHAR                             NOT NULL,
    LABEL      VARCHAR                             NOT NULL,
    TEXT       VARCHAR                             NOT NULL,
    POSITION   INTEGER   DEFAULT 0                 NOT NULL,
    ENABLED    BOOLEAN   DEFAULT TRUE              NOT NULL,
    FAVORITE   BOOLEAN   DEFAULT FALSE             NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX ix_phrase_category_position
    ON phrase (category, position);

-- Same seed as the PostgreSQL migration (see that file for the applied fixes).
INSERT INTO phrase (category, label, text, position, enabled, favorite) VALUES
    ('Анализ',    'История коммитов',        'Покажи историю коммитов файла {{файл}} и объясни ключевые изменения', 0, TRUE, FALSE),
    ('Анализ',    'Поиск коммита по тексту', 'Найди коммит, в котором появился текст «{{текст}}», и покажи его diff', 1, TRUE, FALSE),
    ('Анализ',    'Просмотр изменений',      'Покажи изменения в файле {{файл}} между ревизиями {{от}} и {{до}}',     2, TRUE, FALSE),
    ('Коммиты',   'Имя коммита',             'Опиши незакоммиченные изменения и предложи имя коммита',                0, TRUE, FALSE),
    ('Документы', 'Черновик документа',      'Создай документ-черновик по теме «{{тема}}» с разделами',               0, TRUE, FALSE);
