CREATE TABLE tool_call (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    run_id          VARCHAR(255) NOT NULL,
    call_index      INTEGER NOT NULL DEFAULT 0,
    name            VARCHAR(255) NOT NULL,
    arguments_raw   TEXT,
    status          VARCHAR(20) NOT NULL,
    error           TEXT,
    result_text     TEXT,
    result_meta     TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tool_call UNIQUE (conversation_id, run_id, call_index)
);

CREATE INDEX idx_tool_call_run ON tool_call (conversation_id, run_id);
