-- Индекс call_id -> messageId/responseMessageId вызовов инструментов: заменяет позиционное
-- сопоставление (старые attachRunMeta/backfillToolCallIds) прямым lookup по протокольному id
-- вызова, который уже лежит в chat_message.tool_data. Наполняется на лету при обычном сохранении
-- (ChatMemoryService.saveAll) и бэкафиллом для старых данных (backfillToolCallIndex).
CREATE TABLE tool_call_index (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id      VARCHAR(255) NOT NULL,
    call_id              VARCHAR(255) NOT NULL,
    message_id           BIGINT NOT NULL REFERENCES chat_message (id) ON DELETE CASCADE,
    response_message_id  BIGINT REFERENCES chat_message (id) ON DELETE CASCADE,
    CONSTRAINT uq_tool_call_index UNIQUE (conversation_id, call_id)
);
