spring:
  flyway:
    locations: classpath:db/migration-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./local-db/h2;MODE=PostgreSQL;DEFAULT_NULL_ORDERING=HIGH;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  data:
    jdbc:
      dialect: postgresql

kb:
  search:
    semantic:
      enabled: false

