create sequence if not exists chat_memory_id_seq;

create table if not exists chat_topic
(
    conversation_id varchar                             not null
        primary key,
    "user"          varchar(255)                        not null,
    is_user         boolean                             not null,
    topic           varchar(255),
    created_at      timestamp default CURRENT_TIMESTAMP not null,
    updated_at      timestamp default CURRENT_TIMESTAMP
);

create index if not exists chat_topic_user_timestamp
    on chat_topic ("user" asc, updated_at desc);

create table if not exists chat_message
(
    id              bigint generated by default as identity
        constraint pk_chat_memory
            primary key,
    conversation_id varchar(255),
    content         varchar,
    created_at      timestamp,
    position        bigint                not null,
    summarized      boolean               not null,
    summary         boolean default false not null,
    type            varchar(20)
);

alter sequence chat_memory_id_seq owned by chat_message.id;

create table if not exists documents
(
    id          bigserial
        primary key,
    title       text                                              not null,
    type        text                     default 'document'::text not null,
    parent_id   bigint
        references documents
            on delete cascade,
    description text,
    updated_at  timestamp with time zone default now()            not null
);

-- Stores one embedding row per document.
-- Dimension 1536 matches text-embedding-3-small / text-embedding-ada-002.
-- Use 3072 for text-embedding-3-large.
CREATE TABLE IF NOT EXISTS document_embeddings (
                                                   id             BIGSERIAL PRIMARY KEY,
                                                   document_id    BIGINT NOT NULL UNIQUE
                                                       REFERENCES documents(id) ON DELETE CASCADE,
                                                   embedding      VECTOR(1536) NOT NULL,
                                                   model          TEXT        NOT NULL,
                                                   updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- IVFFlat index for approximate nearest-neighbour search.
-- lists = sqrt(row_count) is a common starting point; tune for your data size.
-- Rebuild (DROP + recreate) whenever you add significant data.
CREATE INDEX IF NOT EXISTS document_embeddings_ivfflat_idx
    ON document_embeddings
        USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);


-- ─────────────────────────────────────────────────────────────────────────────
-- Embedding cache
--
-- Key   : SHA-256 hash of the input text + model name
--         (hex string, 64 chars – stored as TEXT for readability)
-- Value : float[] vector, same VECTOR(1536) type as document_embeddings
--
-- Eviction: EmbeddingCacheCleanupTask deletes rows whose last_used_at
--           is older than the configured TTL (default 30 days).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS embedding_cache (
                                               id           BIGSERIAL    PRIMARY KEY,

    -- SHA-256(text) expressed as lowercase hex (64 chars).
                                               text_hash    CHAR(64)     NOT NULL,

    -- Model name used to produce this embedding, e.g. "text-embedding-3-small".
    -- Included in the lookup key so a model switch doesn't serve stale vectors.
                                               model        TEXT         NOT NULL,

    -- The cached vector. Dimension must match document_embeddings.embedding.
                                               embedding    VECTOR(1536) NOT NULL,

    -- When this row was first inserted.
                                               created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Updated on every cache hit so LRU-style eviction is possible.
                                               last_used_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Composite uniqueness: one vector per (text, model) combination.
                                               CONSTRAINT uq_embedding_cache UNIQUE (text_hash, model)
);

-- Fast equality lookup on (text_hash, model).
CREATE INDEX IF NOT EXISTS idx_embedding_cache_lookup
    ON embedding_cache (text_hash, model);

-- Fast range scan for the cleanup job (DELETE … WHERE last_used_at < ?).
CREATE INDEX IF NOT EXISTS idx_embedding_cache_last_used
    ON embedding_cache (last_used_at);

-- Migration: add ordering support to documents
ALTER TABLE documents ADD COLUMN IF NOT EXISTS position INTEGER NOT NULL DEFAULT 0;

-- ─────────────────────────────────────────────────────────────────────────────
-- Attachments
--
-- A single table for files attached to documents OR chat messages.
-- Exactly one of (document_id, conversation_id) is non-null.
--
-- owner_type is a discriminator: 'document' or 'chat'.
-- content stores the raw text for text-based files (plain text, markdown, csv, …).
-- summary stores an AI-generated description (populated on demand).
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS attachments (
                                           id              BIGSERIAL       PRIMARY KEY,

    -- Polymorphic owner --------------------------------------------------
                                           owner_type      TEXT            NOT NULL CHECK (owner_type IN ('document', 'chat')),
                                           document_id     BIGINT          REFERENCES documents(id) ON DELETE CASCADE,
                                           conversation_id VARCHAR(255)    REFERENCES chat_topic(conversation_id) ON DELETE CASCADE,

    -- File metadata ------------------------------------------------------
                                           file_name       TEXT            NOT NULL,
                                           content_type    TEXT            NOT NULL DEFAULT 'text/plain',
                                           file_size       BIGINT          NOT NULL DEFAULT 0,

    -- Textual content (for text-based attachments) -----------------------
                                           content         TEXT,

    -- AI-generated summary (populated on demand) -------------------------
                                           summary         TEXT,

                                           created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
                                           updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),

    -- Exactly one owner must be set
                                           CONSTRAINT chk_attachment_owner CHECK (
                                               (owner_type = 'document' AND document_id IS NOT NULL AND conversation_id IS NULL) OR
                                               (owner_type = 'chat'     AND conversation_id IS NOT NULL AND document_id IS NULL)
                                               )
);

CREATE INDEX IF NOT EXISTS idx_attachments_document
    ON attachments (document_id) WHERE document_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_attachments_conversation
    ON attachments (conversation_id) WHERE conversation_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- Attachment embeddings (same pattern as document_embeddings)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS attachment_embeddings (
                                                     id              BIGSERIAL       PRIMARY KEY,
                                                     attachment_id   BIGINT          NOT NULL UNIQUE
                                                         REFERENCES attachments(id) ON DELETE CASCADE,
                                                     embedding       VECTOR(1536)    NOT NULL,
                                                     model           TEXT            NOT NULL,
                                                     updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS attachment_embeddings_ivfflat_idx
    ON attachment_embeddings
        USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
