create sequence if not exists chat_memory_id_seq;

create table if not exists chat_topic
(
    conversation_id varchar                             not null
        primary key,
    "user"          varchar(255)                        not null,
    is_user         boolean                             not null,
    topic           varchar(255),
    created_at      timestamp default CURRENT_TIMESTAMP not null,
    updated_at      timestamp default CURRENT_TIMESTAMP
);

create index if not exists chat_topic_user_timestamp
    on chat_topic ("user" asc, updated_at desc);

create table if not exists chat_message
(
    id              bigint generated by default as identity
        constraint pk_chat_memory
            primary key,
    conversation_id varchar(255),
    content         varchar,
    created_at      timestamp,
    position        bigint                not null,
    summarized      boolean               not null,
    summary         boolean default false not null,
    type            varchar(20)
);

alter sequence chat_memory_id_seq owned by chat_message.id;

create table if not exists documents
(
    id          bigserial
        primary key,
    title       text                                              not null,
    type        text                     default 'document'::text not null,
    parent_id   bigint
        references documents
            on delete cascade,
    description text,
    updated_at  timestamp with time zone default now()            not null
);

-- Stores one embedding row per document.
-- Dimension 1536 matches text-embedding-3-small / text-embedding-ada-002.
-- Use 3072 for text-embedding-3-large.
CREATE TABLE IF NOT EXISTS document_embeddings (
                                                   id             BIGSERIAL PRIMARY KEY,
                                                   document_id    BIGINT NOT NULL UNIQUE
                                                       REFERENCES documents(id) ON DELETE CASCADE,
                                                   embedding      VECTOR(1536) NOT NULL,
                                                   model          TEXT        NOT NULL,
                                                   updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- IVFFlat index for approximate nearest-neighbour search.
-- lists = sqrt(row_count) is a common starting point; tune for your data size.
-- Rebuild (DROP + recreate) whenever you add significant data.
CREATE INDEX IF NOT EXISTS document_embeddings_ivfflat_idx
    ON document_embeddings
        USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
